spring.application.name=k_enterprise
server.port=8282
spring.datasource.url=jdbc:postgresql://localhost:5432/krb_enterprise
spring.datasource.username=krb
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.open-in-view=false